# Release configuration for ggl

[workspace]
allow_dirty = true # allow updating repositories with uncommitted changes
features_always_increment_minor = true

[[package]]
name = "ggl"
changelog_update = true # enable changelog update
publish = true

[[package]]
name = "ggl_wasm"
publish = false

[[package]]
name = "ggl_cli"
publish = false

[[package]]
name = "ggl_client"
publish = false

[changelog]
protect_breaking_commits = true # always include commits with breaking changes in the changelog
