# Release configuration for ggl
[workspace]
allow_dirty = true # allow updating repositories with uncommitted changes
features_always_increment_minor = true
pr_branch_prefix = "ggl_release" # PR branch prefix
dependencies_update = true # update dependencies with `cargo update`

[[package]]
name = "graph_generation_language"
changelog_update = true # enable changelog update
publish = true

[[package]]
name = "ggl_wasm"
publish = false

[[package]]
name = "ggl_cli"
publish = false

[[package]]
name = "ggl_client"
publish = false

[changelog]
protect_breaking_commits = true # always include commits with breaking changes in the changelog
