# Omnix configuration for ggl
# This ensures consistent CI behavior across platforms

[ci.options]
# Increase timeout for WASM builds which can be slow
timeout = 3600
# Use more verbose output for debugging
verbose = false
