[package]
name = "ggl_wasm"
version.workspace = true
edition.workspace = true
license.workspace = true


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ggl = { path = "../ggl" }
wasm-bindgen = "0.2"
